min_version = "2025.7.0"

[tools]
bun = "latest"
elixir = "latest"
erlang = "latest"
hk = "latest"
"npm:prettier" = "latest"
pkl = "latest"
"ubi:wilsonzlin/minify-html" = "latest"

[settings]
experimental = true
lockfile = true

[settings.npm]
bun = true
